### ISSUE TITLE
Publish to GitHub Pages

### ISSUE THREAD

**Issue by michey85** [michey85/IPAdress#26]
Setup GitHub Pages page for the app.

**Comment by LazarevSlava** [comment]
I have a problem. I checked information and create a public page for a new repository, but for our repository i have not enough  administrator rightsю I haven't "settings"

**Comment by michey85** [comment]
> I have a problem. I checked information and create a public page for a new repository, but for our repository i have not enough administrator rightsю I haven't "settings"

How can I help you with this? I can set any settings you ask.

**Comment by LazarevSlava** [comment]
see please new pull request 
i installed some dependency and changed packeage.json
i think we need merge it and do steps:
1 Push the React app to the GitHub repository:
npm run deploy
2 Configure GitHub Pages
- Navigate to the GitHub Pages settings page
- In your web browser, navigate to the GitHub repository
- Above the code browser, click on the tab labeled "Settings"
- In the sidebar, in the "Code and automation" section, click on "Pages"
- Configure the "Build and deployment" settings like this:
- Source: Deploy from a branch
- Branch: gh-pages
- Folder: / (root)
- Click on the "Save" button

**Comment by LazarevSlava** [comment]
maybe we need anoother one step:
Add a "remote" to the local Git repository:
$ git remote add origin https://github.com/michey85/{repo-name}.git


And we must enter michey85.github.io as the repository name

**Comment by michey85** [comment]
Okay. I left a comment to your new branch. Fix it and marge then.
